export const CSHARP_PROJECT_REQUEST = 'CSHARP_PROJECT_REQUEST'
export const CSHARP_PROJECT_SUCCESS = 'CSHARP_PROJECT_SUCCESS'
export const CSHARP_PROJECT_FAIL = 'CSHARP_PROJECT_FAIL'

export const CSHARP_DETAIL_REQUEST = 'CSHARP_DETAIL_REQUEST'
export const CSHARP_DETAIL_SUCCESS = 'CSHARP_DETAIL_SUCCESS'
export const CSHARP_DETAIL_FAIL = 'CSHARP_DETAIL_FAIL'

export const CSHARP_COUNT_REQUEST = 'CSHARP_COUNT_REQUEST'
export const CSHARP_COUNT_SUCCESS = 'CSHARP_COUNT_SUCCESS'
export const CSHARP_COUNT_FAIL = 'CSHARP_COUNT_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'