export const HTML_COUNT_REQUEST = 'HTML_COUNT_REQUEST'
export const HTML_COUNT_SUCCESS = 'HTML_COUNT_SUCCESS'
export const HTML_COUNT_FAIL = 'HTML_COUNT_FAIL'

export const HTML_PROJECT_REQUEST = 'HTML_PROJECT_REQUEST'
export const HTML_PROJECT_SUCCESS = 'HTML_PROJECT_SUCCESS'
export const HTML_PROJECT_FAIL = 'HTML_PROJECT_FAIL'

export const HTML_DETAIL_REQUEST = 'HTML_DETAIL_REQUEST'
export const HTML_DETAIL_SUCCESS = 'HTML_DETAIL_SUCCESS'
export const HTML_DETAIL_FAIL = 'HTML_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'