
export const JAVA_COUNT_REQUEST = 'JAVA_COUNT_REQUEST'
export const JAVA_COUNT_SUCCESS = 'JAVA_COUNT_SUCCESS'
export const JAVA_COUNT_FAIL = 'JAVA_COUNT_FAIL'

export const JAVA_PROJECT_REQUEST = 'JAVA_PROJECT_REQUEST'
export const JAVA_PROJECT_SUCCESS = 'JAVA_PROJECT_SUCCESS'
export const JAVA_PROJECT_FAIL = 'JAVA_PROJECT_FAIL'

export const JAVA_DETAIL_REQUEST = 'JAVA_DETAIL_REQUEST'
export const JAVA_DETAIL_SUCCESS = 'JAVA_DETAIL_SUCCESS'
export const JAVA_DETAIL_FAIL = 'JAVA_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'